"""System-generated messages stored in the database (review reasons, provenance, change notes).

They are stored as language-neutral tokens ⟦{"k": key, ...params}⟧ and rendered in the viewer's
language by the `sysmsg` template filter, so nothing generated by the app is frozen in one language.
Plain text (e.g. written by the curator) passes through unchanged."""
import json
import re

MESSAGES = {
    "manual_entry": ("Entered manually", "Įvesta rankiniu būdu"),
    "admin_link": ("Link added by an administrator", "Nuoroda įvesta administratoriaus"),
    "suggested_by": ("Suggested by {email}", "Pasiūlė {email}"),
    "user_suggestion": ("User suggestion ({email})", "Naudotojo pasiūlymas ({email})"),
    "comment": ("Comment: {text}", "Komentaras: {text}"),
    "added_cli": ("Added from the command line", "Pridėta per komandinę eilutę"),
    "created": ("Created", "Sukurta"),
    "deadline_passed": ("Deadline {date} has passed", "Terminas {date} praėjo"),
    "auto_check": ("Automatic check on the organiser's page", "Automatinė patikra organizatoriaus puslapyje"),
    "call_opened": ("The call has opened", "Kvietimas atsidarė"),
    "page_closed": ("The page says the call is closed although the deadline has not passed",
                    "Puslapis rodo, kad kvietimas uždarytas, nors terminas dar nepraėjo"),
    "auto_updated": ("Updated automatically: {changes}", "Automatiškai atnaujinta: {changes}"),
    "link_broken": ("The link does not work ({status})", "Nuoroda neveikia ({status})"),
    "heuristic": ("Read automatically without AI — check every field.",
                  "Nuskaityta automatiškai be AI — patikrinkite visus laukus."),
    "site_blocked": ("The site blocks automatic reading (HTTP {status}) — paste the page text instead",
                     "Svetainė blokuoja automatinį nuskaitymą (HTTP {status}) — įklijuokite puslapio tekstą"),
    "page_unreachable": ("Could not open the page: {error}", "Nepavyko atidaryti puslapio: {error}"),
    "possible_duplicate_link": ("Possible duplicate of #{id} (same link)", "Galimas dublikatas: #{id} (ta pati nuoroda)"),
    "possible_duplicate_title": ("Possible duplicate of #{id} (similar title)", "Galimas dublikatas: #{id} (panašus pavadinimas)"),
    "expected_next": ("Expected next call of the series (created automatically)",
                      "Laukiamas kitas serijos kvietimas (sukurta automatiškai)"),
    "found_in_series": ("New call found on the series page: {name}", "Serijos puslapyje rastas naujas kvietimas: {name}"),
    "new_edition": ("The page now shows a different call (new edition or theme) — a new entry #{id} was created for review instead of changing this one",
                    "Puslapyje dabar kitas kvietimas (nauja laida ar tema) — vietoj šio įrašo keitimo sukurtas naujas įrašas #{id} peržiūrai"),
    "expected_missing": ("The expected call of this series was not found by {date} — check the series page",
                         "Laukiamas šios serijos kvietimas iki {date} nerastas — patikrinkite serijos puslapį"),
    "auto_translated": ("Missing translations filled in automatically", "Trūkstami vertimai užpildyti automatiškai"),
}

TOKEN = re.compile(r"⟦(\{.*?\})⟧")


def msg(key, **params):
    return "⟦" + json.dumps({"k": key, **params}, ensure_ascii=False) + "⟧"


def render(text, lang="lt"):
    if not text or "⟦" not in text:
        return text or ""

    def one(m):
        try:
            data = json.loads(m.group(1))
            en, lt = MESSAGES[data.pop("k")]
            return (lt if lang == "lt" else en).format(**data)
        except (ValueError, KeyError):
            return m.group(0)
    return TOKEN.sub(one, text)
