"""english organiser and source

Revision ID: 145ad730b12e
Revises: b69bfa856ad9
Create Date: 2026-10-05 11:40:20.390093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145ad730b12e'
down_revision = 'b69bfa856ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_en', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('source_en', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.drop_column('source_en')
        batch_op.drop_column('org_en')

    # ### end Alembic commands ###
