"""initial schema

Revision ID: 2dfe98d6ce78
Revises: 
Create Date: 2026-09-29 12:18:01.728619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dfe98d6ce78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('checked', sa.Integer(), nullable=True),
    sa.Column('changed', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('ms_oid', sa.String(length=64), nullable=True),
    sa.Column('ms_tid', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('lang', sa.String(length=2), nullable=True),
    sa.Column('calendar_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_token'),
    sa.UniqueConstraint('ms_oid')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=True),
    sa.Column('star', sa.Boolean(), nullable=True),
    sa.Column('title_lt', sa.String(length=400), nullable=True),
    sa.Column('title_en', sa.String(length=400), nullable=True),
    sa.Column('org', sa.String(length=400), nullable=True),
    sa.Column('city_lt', sa.String(length=160), nullable=True),
    sa.Column('city_en', sa.String(length=160), nullable=True),
    sa.Column('country_lt', sa.String(length=160), nullable=True),
    sa.Column('country_en', sa.String(length=160), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('deadline_word_lt', sa.String(length=300), nullable=True),
    sa.Column('deadline_word_en', sa.String(length=300), nullable=True),
    sa.Column('event_start', sa.Date(), nullable=True),
    sa.Column('event_end', sa.Date(), nullable=True),
    sa.Column('expires', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('desc_lt', sa.Text(), nullable=True),
    sa.Column('desc_en', sa.Text(), nullable=True),
    sa.Column('topics', sa.String(length=400), nullable=True),
    sa.Column('kam_tinka', sa.Text(), nullable=True),
    sa.Column('nauda', sa.Text(), nullable=True),
    sa.Column('mokestis', sa.Text(), nullable=True),
    sa.Column('amzius', sa.Text(), nullable=True),
    sa.Column('padengiama', sa.Text(), nullable=True),
    sa.Column('nuotoliu', sa.Text(), nullable=True),
    sa.Column('registracija', sa.Text(), nullable=True),
    sa.Column('studentu_nuolaida', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=400), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('first_seen', sa.String(length=40), nullable=True),
    sa.Column('last_verified', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_expires'), ['expires'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_needs_review'), ['needs_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_url'), ['url'], unique=False)

    op.create_table('call_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('origin', sa.String(length=24), nullable=True),
    sa.Column('field', sa.String(length=60), nullable=True),
    sa.Column('old', sa.Text(), nullable=True),
    sa.Column('new', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_change', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_change_call_id'), ['call_id'], unique=False)

    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'call_id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_call_id'))

    op.drop_table('subscription')
    with op.batch_alter_table('call_change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_change_call_id'))

    op.drop_table('call_change')
    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_url'))
        batch_op.drop_index(batch_op.f('ix_call_status'))
        batch_op.drop_index(batch_op.f('ix_call_needs_review'))
        batch_op.drop_index(batch_op.f('ix_call_kind'))
        batch_op.drop_index(batch_op.f('ix_call_expires'))
        batch_op.drop_index(batch_op.f('ix_call_deadline'))
        batch_op.drop_index(batch_op.f('ix_call_country_code'))

    op.drop_table('call')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('refresh_run')
    # ### end Alembic commands ###
