"""series listing pages

Revision ID: 76fbf5b29fed
Revises: 8aa4bd6dc0af
Create Date: 2026-10-05 23:53:10.461603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fbf5b29fed'
down_revision = '8aa4bd6dc0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_aggregator', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('is_aggregator')

    # ### end Alembic commands ###
