"""fields, categories, disciplines, email log

Revision ID: 8aa4bd6dc0af
Revises: d8895ba73339
Create Date: 2026-10-05 23:21:08.713924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa4bd6dc0af'
down_revision = 'd8895ba73339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name_lt', sa.String(length=120), nullable=True),
    sa.Column('name_en', sa.String(length=120), nullable=True),
    sa.Column('hue', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('name_lt', sa.String(length=120), nullable=True),
    sa.Column('name_en', sa.String(length=120), nullable=True),
    sa.Column('hue', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_field_id'), ['field_id'], unique=False)

    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('to', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=400), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_to'), ['to'], unique=False)

    op.create_table('discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name_lt', sa.String(length=120), nullable=True),
    sa.Column('name_en', sa.String(length=120), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('discipline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discipline_category_id'), ['category_id'], unique=False)

    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fields', sa.String(length=200), server_default='', nullable=False))

    # ### end Alembic commands ###
    _seed_taxonomy_and_assign_fields()


# Initial tree, frozen here so this migration always produces the same result.
FIELDS = [("music", "Muzika ir garsas", "Music and Sound", 212), ("theatre", "Teatras", "Theatre", 8),
          ("cinema", "Kinas", "Cinema", 280), ("dance", "Šokis ir performansas", "Dance and Performance", 142)]


def _seed_taxonomy_and_assign_fields():
    """Default fields / categories / sub-disciplines, then every existing entry gets Music and Sound
    plus Theatre / Cinema / Dance only where its title says so unmistakably (title-only rules; the rest
    can be refined with `flask classify-fields` or by hand)."""
    import re
    from app.taxonomy import DEFAULT_TREE   # the same tree new installs get
    conn = op.get_bind()
    field = sa.table("field", sa.column("id", sa.Integer), sa.column("key", sa.String), sa.column("name_lt", sa.String),
                     sa.column("name_en", sa.String), sa.column("hue", sa.Integer), sa.column("position", sa.Integer))
    category = sa.table("category", sa.column("id", sa.Integer), sa.column("key", sa.String), sa.column("field_id", sa.Integer),
                        sa.column("name_lt", sa.String), sa.column("name_en", sa.String), sa.column("hue", sa.Integer),
                        sa.column("position", sa.Integer))
    discipline = sa.table("discipline", sa.column("key", sa.String), sa.column("category_id", sa.Integer),
                          sa.column("name_lt", sa.String), sa.column("name_en", sa.String), sa.column("position", sa.Integer))
    if conn.execute(sa.text("SELECT COUNT(*) FROM field")).scalar():
        return
    for i, (key, lt, en, hue) in enumerate(FIELDS):
        conn.execute(field.insert().values(key=key, name_lt=lt, name_en=en, hue=hue, position=i))
    fid = {k: i for i, k in conn.execute(sa.text("SELECT id, key FROM field")).fetchall()}
    for i, (key, fkey, lt, en, hue, discs) in enumerate(DEFAULT_TREE):
        conn.execute(category.insert().values(key=key, field_id=fid.get(fkey), name_lt=lt, name_en=en, hue=hue, position=i))
        cid = conn.execute(sa.text("SELECT id FROM category WHERE key = :k"), {"k": key}).scalar()
        for j, (dkey, dlt, den) in enumerate(discs):
            conn.execute(discipline.insert().values(key=dkey, category_id=cid, name_lt=dlt, name_en=den, position=j))

    rules = {"theatre": r"music[- ]theat|muzikin\w* teatr|\boperos?\b|\btheat(re|er)\b|\bteatr",
             "cinema": r"film music|cin[eé]ma|kino muzik|\bkin(as|o)\b|\bfilms?\b|filmų|filmo",
             "dance": r"\bdanc(e|ers?|ing)\b|choreograph|\bšok(is|io|ėj)|choreograf"}
    for cid, t_en, t_lt, topics in conn.execute(sa.text("SELECT id, title_en, title_lt, topics FROM call")).fetchall():
        title = f"{t_en or ''} {t_lt or ''}"
        fields = ["music"] + [k for k, p in rules.items() if re.search(p, title, re.I)]
        topics = (topics or "").replace(",theatre,", ",drama,")   # old "theatre & dance" topic → drama
        if "drama" in topics and "theatre" not in fields:
            fields.append("theatre")
        conn.execute(sa.text("UPDATE call SET fields = :f, topics = :t WHERE id = :i"),
                     {"f": "," + ",".join(fields) + ",", "t": topics, "i": cid})


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.drop_column('fields')

    with op.batch_alter_table('discipline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discipline_category_id'))

    op.drop_table('discipline')
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_log_to'))
        batch_op.drop_index(batch_op.f('ix_email_log_at'))

    op.drop_table('email_log')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_field_id'))

    op.drop_table('category')
    op.drop_table('field')
    # ### end Alembic commands ###
