"""translations and email reminders

Revision ID: b69bfa856ad9
Revises: 2dfe98d6ce78
Create Date: 2026-09-30 20:04:32.812921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69bfa856ad9'
down_revision = '2dfe98d6ce78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_sent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'call_id', 'kind', 'deadline')
    )
    with op.batch_alter_table('reminder_sent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_sent_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_sent_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kam_tinka_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nauda_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mokestis_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('amzius_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('padengiama_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nuotoliu_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('registracija_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('studentu_nuolaida_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('note_en', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_reminders', sa.Boolean(), server_default=sa.true(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_reminders')

    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.drop_column('note_en')
        batch_op.drop_column('studentu_nuolaida_en')
        batch_op.drop_column('registracija_en')
        batch_op.drop_column('nuotoliu_en')
        batch_op.drop_column('padengiama_en')
        batch_op.drop_column('amzius_en')
        batch_op.drop_column('mokestis_en')
        batch_op.drop_column('nauda_en')
        batch_op.drop_column('kam_tinka_en')

    with op.batch_alter_table('reminder_sent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_sent_user_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_sent_call_id'))

    op.drop_table('reminder_sent')
    # ### end Alembic commands ###
