"""series, follows, notifications

Revision ID: d8895ba73339
Revises: 145ad730b12e
Create Date: 2026-10-05 20:13:05.575830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8895ba73339'
down_revision = '145ad730b12e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_lt', sa.String(length=300), nullable=True),
    sa.Column('name_en', sa.String(length=300), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=True),
    sa.Column('org', sa.String(length=400), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('recurrence', sa.String(length=16), nullable=True),
    sa.Column('typical_month', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('last_found_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series_follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'series_id')
    )
    with op.batch_alter_table('series_follow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_follow_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_follow_user_id'), ['user_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_placeholder', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('announced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('admin_notified_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_call_series_id'), ['series_id'], unique=False)
        batch_op.create_foreign_key('fk_call_series_id', 'series', ['series_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_series', sa.Boolean(), server_default=sa.true(), nullable=False))
        batch_op.add_column(sa.Column('email_admin', sa.Boolean(), server_default=sa.true(), nullable=False))

    # ### end Alembic commands ###

    # Weekly reminders need several rows per (user, call, deadline): rebuild reminder_sent without its
    # old unique constraint, keeping the rows (portable: works the same on SQLite and PostgreSQL).
    op.create_table('reminder_sent_new',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('call_id', sa.Integer(), nullable=False),
        sa.Column('kind', sa.String(length=24), nullable=True),
        sa.Column('deadline', sa.Date(), nullable=True),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['call_id'], ['call.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'))
    op.execute('INSERT INTO reminder_sent_new (id, user_id, call_id, kind, deadline, sent_at) '
               'SELECT id, user_id, call_id, kind, deadline, sent_at FROM reminder_sent')
    op.drop_table('reminder_sent')
    op.rename_table('reminder_sent_new', 'reminder_sent')
    op.create_index('ix_reminder_sent_user_id', 'reminder_sent', ['user_id'])
    op.create_index('ix_reminder_sent_call_id', 'reminder_sent', ['call_id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_admin')
        batch_op.drop_column('email_series')

    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.drop_constraint('fk_call_series_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_call_series_id'))
        batch_op.drop_column('admin_notified_at')
        batch_op.drop_column('announced_at')
        batch_op.drop_column('is_placeholder')
        batch_op.drop_column('series_id')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_sent_at'))
        batch_op.drop_index(batch_op.f('ix_notification_call_id'))

    op.drop_table('notification')
    with op.batch_alter_table('series_follow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_follow_user_id'))
        batch_op.drop_index(batch_op.f('ix_series_follow_series_id'))

    op.drop_table('series_follow')
    op.drop_table('series')
    # ### end Alembic commands ###
